### ISSUE TITLE
view "/error" not found

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-core#237] opened 2022-04-12 11:05 UTC
This error was generated by Grails 3.3.9 in the Admin app when an export that exceeds 20MB was blocked by one of the app's containers (Tomcat or Docker) or proxies (nginx, rancher) -- I'm pretty sure it was the Tomcat container, but just keeping the other options in mind:

`    "serverDetails": "{\"timestamp\":1649708816626,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"org.springframework.web.multipart.MultipartException\",\"message\":\"Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'\",\"path\":\"/xh/export\"}"`

It looks like our Hoist-Core plugin does not provide a view  called `/error` which Grails expects to be defined.

If we address this, we probably want to do so in our active Grails 5 version of Hoist-Core.

**Comment by cnrudd** [comment] 2022-04-18 14:50
In our Grails 5 branch it looks like this error is being handled correctly.  This error was created by trying to export data from:
http://localhost:3000/admin/tests/grid on a local instance of toolbox.
    

"serverDetails": "{\"timestamp\":1650292715485,\"status\":500,\"error\":\"Internal Server Error\",\"trace\":\"org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (21505754) exceeds the configured maximum (20971520)\\n\\tat org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:122)\\n\\tat org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:115)\\n\\tat org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.(StandardMultipartHttpServletRequest.java:88)\\n\\tat org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:122)\\n\\tat org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1205)\\n\\tat org.grails.web.servlet.mvc.GrailsDispatcherServlet.checkMultipart(GrailsDispatcherServlet.groovy:76)\\n\\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)\\n\\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)\\n\\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\\n\\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\\n\\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\\n\\tat org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)\\n\\tat org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)\\n\\tat io.xh.hoist.security.HoistSecurityFilter.doFilter(HoistSecurityFilter.groovy:27)\\n\\tat java.base/java.lang.Thread.run(Thread.java:829)\\nCaused by: java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (21505754) exceeds the configured maximum (20971520)\\n\\tat org.grails.web.filters.HiddenHttpMethodFilter.getHttpMethodOverride(HiddenHttpMethodFilter.java:71)\\n\\tat org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:60)\\n\\t... 2 more\\nCaused by: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (21505754) exceeds the configured maximum (20971520)\\n\\t... 4 more\\n\",\"message\":\"Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (21505754) exceeds the configured maximum (20971520)\",\"path\":\"/xh/export\"}",

**Comment by amcclain** [comment] 2022-04-18 16:22
We always want to be serializing our exceptions to JSON, so we don't expect to be rendering an error.gsp with other markup. It looks like this particular exception wasn't triggering the JSON exception rendering in the prior Grails 3 based version of hoist-core, but now it is rendering JSON as intended.

Leaving aside the exception itself - related to max upload sizes - I'd vote for closing this ticket if we are seeing the correct serialization in the latest Grails 5 based library. We've lived with the occasional reference to a missing error.gsp for years, so I don't see any need to back-port or research a fix for the old Grails3 version.

**Closed** 2022-04-18 17:34 UTC
Labels: bug, technical, small
